- hosts: localhost
  roles:
    - emit-job-header
    - log-inventory

- hosts: all
  tasks:
    - name: Install packages
      package:
        name:
          - git
          - rsync
        state: present

- hosts: all
  roles:
    - add-build-sshkey
    - start-zuul-console
    - ensure-output-dirs
    - prepare-workspace-git
