- hosts: localhost
  roles:
    - emit-job-header
    - log-inventory

- hosts: all
  tasks:
    - name: Update apt cache
      become: yes
      command: apt-get update
    - name: Install packages
      become: true
      package:
        name:
          - git
          - rsync
        state: present

- hosts: all
  roles:
    - add-build-sshkey
    - start-zuul-console
    - ensure-output-dirs
    - prepare-workspace-git
